### ISSUE TITLE
locale on gh-pages

### ISSUE THREAD

**Issue by tsamaya** [tomwayson/responsive-citizens#1]
Take care of locale at root locale files, with my default locale 'fr', I got three 404 with these files and the application do not start:
- http://tomwayson.github.io/responsive-citizens/dojo/cldr/nls/fr/gregorian.js 
- http://tomwayson.github.io/responsive-citizens/dojo/cldr/nls/fr/number.js 
- http://tomwayson.github.io/responsive-citizens/esri/nls/fr/jsapi.js

**Comment by tomwayson** [comment]
Good catch! I tried to deploy just the files needed to support the built code. Looks like I need to add nls files to this list:

https://github.com/tomwayson/responsive-citizens/blob/master/gruntfile.js#L142

**Comment by tsamaya** [comment]
A first alternative to the nls file is afer `grunt slurp` edit file `responsive-citizens/src/esri/nls/jsapi.js` and put each locale value from 1 to 0.

A second one, not efficient in terms of page load is to include all locales `into app.profile.js` like this:
https://github.com/tsamaya/responsive-citizens/blob/master/profiles/app.profile.js#L90

**Comment by tomwayson** [comment]
Fixed in 732d3a2acbb386479750c14877ed87e8792e5f8a
