### ISSUE TITLE
404 on live view

### ISSUE THREAD

**Issue by MattPil29** [tomwayson/responsive-citizens#10]
Hi, 
I tried to view your example but at least one resource appears to be missing:
/responsive-citizens/dojo/nls/dojo_en-gb.js 

Thanks, Matt

**Comment by tomwayson** [comment]
Thanks @MattPil29. Did this prevent the page from loading/working, or was it just something that you noticed in the console?

**Comment by MattPil29** [comment]
@tomwayson Yes it prevented the load.  I used IE Network tab to quickly see the missing resource.  No messages in the console.

**Comment by tomwayson** [comment]
OK, thanks. I think this is related to #1 and there may be a fix in #9 for this. Somehow I missed the fact that this was causing the app to not load (sorry @tsamaya). I will make this a priority.

**Comment by tomwayson** [comment]
@MattPil29, I've included the nls files on the gh-pages site. Can you please confirm that this fixes your locale issues (may require a hard refresh)?

**Comment by MattPil29** [comment]
@tomwayson it is working now - thanks for the top support.

**Comment by tomwayson** [comment]
Thanks @MattPil29!
